((System.Action)(() => {
if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Probe requires Play Mode.");
var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>(); var player=UnityEngine.GameObject.Find("PlayerNew"); var camera=UnityEngine.Camera.main;
var switcher=terrain?terrain.GetComponent("TerrainRoadV3RuntimeSwitcher") as UnityEngine.Behaviour:null; var input=player?player.GetComponent("PlayerInputNew"):null; var movement=player?player.GetComponent("FirstPersonController") as UnityEngine.MonoBehaviour:null;
if(!terrain||!player||!camera||switcher==null||input==null||movement==null)throw new System.Exception("Required scene components missing.");
var type=switcher.GetType();var variant=type.GetProperty("CurrentVariant");var runtimeProp=type.GetProperty("RuntimeData");var layersProp=type.GetProperty("RuntimeLayers");var sourceField=type.GetField("sourceLayers",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var v4Field=type.GetField("v4TemplateLayers",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var normalAField=type.GetField("normalA",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var normalBField=type.GetField("normalB",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);
if(variant==null||runtimeProp==null||layersProp==null||sourceField==null||v4Field==null||normalAField==null||normalBField==null)throw new System.Exception("Expected V4 switcher fields/properties unavailable.");
var originalData=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainData>("Assets/Art/Environment/TerrainRoadLookdev/RoadsideV1/TerrainData/TD_TerrainRoad_RoadsideV1.asset");var collider=terrain.GetComponent<UnityEngine.TerrainCollider>();if(!originalData||collider==null)throw new System.Exception("Roadside V1 terrain baseline missing.");
string scenePath=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path; string sceneHash;using(var sha=System.Security.Cryptography.SHA256.Create())sceneHash=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(scenePath))).Replace("-","");
var heights=originalData.GetHeights(0,0,originalData.heightmapResolution,originalData.heightmapResolution);var alphas=originalData.GetAlphamaps(0,0,originalData.alphamapWidth,originalData.alphamapHeight);
var source=(UnityEngine.TerrainLayer[])sourceField.GetValue(switcher);var v4=(UnityEngine.TerrainLayer[])v4Field.GetValue(switcher);var nA=(UnityEngine.Texture2D)normalAField.GetValue(switcher);var nB=(UnityEngine.Texture2D)normalBField.GetValue(switcher);var sourceDiff=new UnityEngine.Texture2D[3];var sourceNorm=new UnityEngine.Texture2D[3];var sourceMask=new UnityEngine.Texture2D[3];for(int i=0;i<3;i++){sourceDiff[i]=source[i].diffuseTexture;sourceNorm[i]=source[i].normalMapTexture;sourceMask[i]=source[i].maskMapTexture;}
var playerPos=player.transform.position;var playerRot=player.transform.rotation;var cameraLocalRot=camera.transform.localRotation;var cameraPos=camera.transform.position;var keyboard=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Keyboard>("RoadV4ProbeKeyboard");var errors=new System.Collections.Generic.List<string>();UnityEngine.Application.LogCallback log=(m,s,k)=>{if(k==UnityEngine.LogType.Error||k==UnityEngine.LogType.Exception||k==UnityEngine.LogType.Assert){errors.Add(k+":"+m);System.IO.File.WriteAllText("Artifacts/TerrainRoadV4_1/TerrainRoadV4_PlayerLoopProbe.json","{\"passed\":false,\"error\":\""+m.Replace("\\","\\\\").Replace("\"","\\\"")+"\"}",new System.Text.UTF8Encoding(false));}};UnityEngine.Application.logMessageReceived+=log;var focus=UnityEditor.EditorWindow.focusedWindow;var gameViewType=System.Type.GetType("UnityEditor.GameView, UnityEditor");if(gameViewType!=null){var gv=UnityEditor.EditorWindow.GetWindow(gameViewType);if(gv!=null)gv.Focus();}
var snapshots=new System.Collections.Generic.List<string>();
System.Collections.IEnumerator Probe(){int frames=0;float moveDelta=0f,cameraDelta=0f;var firstRuntime=(UnityEngine.TerrainData)runtimeProp.GetValue(switcher,null);var firstLayers=(UnityEngine.TerrainLayer[])layersProp.GetValue(switcher,null);try{
 for(int i=0;i<2;i++){yield return null;frames++;} if(variant.GetValue(switcher,null).ToString()!="V3B")throw new System.Exception("Play entry did not start at V3B.");
 UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return null;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F7));yield return null;frames+=2;if(variant.GetValue(switcher,null).ToString()!="V3B")throw new System.Exception("F7 did not select V3B.");
 UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return null;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F8));yield return null;frames+=2;if(variant.GetValue(switcher,null).ToString()!="V4")throw new System.Exception("F8 did not select V4.");var run=(UnityEngine.TerrainLayer[])layersProp.GetValue(switcher,null);for(int i=0;i<3;i++){if(run[i].diffuseTexture!=v4[i].diffuseTexture||run[i].normalMapTexture!=v4[i].normalMapTexture||run[i].maskMapTexture!=v4[i].maskMapTexture)throw new System.Exception("V4 map mismatch on road layer "+i);if(run[i].diffuseRemapMin.w!=0f||run[i].diffuseRemapMax.w!=1f)throw new System.Exception("V4 diffuse alpha remap invalid.");}
 UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return null;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F7));yield return null;frames+=2;if(variant.GetValue(switcher,null).ToString()!="V3B")throw new System.Exception("Repeated switch F8->F7 failed."); UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return null;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F8));yield return null;frames+=2;if(variant.GetValue(switcher,null).ToString()!="V4")throw new System.Exception("Repeated switch F7->F8 failed."); Vector3 p0=player.transform.position,c0=camera.transform.position;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.W));for(int i=0;i<24;i++){yield return null;frames++;}moveDelta=UnityEngine.Vector3.Distance(p0,player.transform.position);cameraDelta=UnityEngine.Vector3.Distance(c0,camera.transform.position);UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());for(int i=0;i<2;i++){yield return null;frames++;}if(moveDelta<.1f||cameraDelta<.01f)throw new System.Exception("W input did not move player/camera sufficiently: "+moveDelta+"/"+cameraDelta);
 UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F6));yield return null;frames++;if(variant.GetValue(switcher,null).ToString()!="V3A")throw new System.Exception("F6 did not select V3A.");run=(UnityEngine.TerrainLayer[])layersProp.GetValue(switcher,null);for(int i=0;i<3;i++)if(run[i].diffuseTexture!=sourceDiff[i]||run[i].normalMapTexture!=nA||run[i].maskMapTexture!=sourceMask[i])throw new System.Exception("V3A map restore failed on layer "+i);
 UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return null;UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.F7));yield return null;frames+=2;if(variant.GetValue(switcher,null).ToString()!="V3B")throw new System.Exception("F7 did not restore V3B.");run=(UnityEngine.TerrainLayer[])layersProp.GetValue(switcher,null);for(int i=0;i<3;i++)if(run[i].diffuseTexture!=sourceDiff[i]||run[i].normalMapTexture!=nB||run[i].maskMapTexture!=sourceMask[i])throw new System.Exception("V3B map restore failed on layer "+i);
 if(terrain.terrainData!=firstRuntime||collider.terrainData!=firstRuntime||firstRuntime.terrainLayers.Length<4)throw new System.Exception("Runtime terrain/collider refs changed unexpectedly.");switcher.enabled=false;yield return null;frames++;if(terrain.terrainData!=originalData||collider.terrainData!=originalData||firstRuntime!=null)throw new System.Exception("Disable did not restore original terrain/collider and destroy runtime TD.");switcher.enabled=true;yield return null;frames++;var second=(UnityEngine.TerrainData)runtimeProp.GetValue(switcher,null);if(second==null||second==firstRuntime||terrain.terrainData!=second||collider.terrainData!=second||variant.GetValue(switcher,null).ToString()!="V3B")throw new System.Exception("Reenable did not create fresh runtime copies starting at V3B.");var secondLayers=(UnityEngine.TerrainLayer[])layersProp.GetValue(switcher,null);if(secondLayers.Length!=3||secondLayers[0]==firstLayers[0])throw new System.Exception("Runtime layer copies did not refresh.");
 var heightAfter=originalData.GetHeights(0,0,originalData.heightmapResolution,originalData.heightmapResolution);var alphaAfter=originalData.GetAlphamaps(0,0,originalData.alphamapWidth,originalData.alphamapHeight);if(!HeightsSame(heights,heightAfter)||!AlphasSame(alphas,alphaAfter))throw new System.Exception("Source terrain height/alphamap changed.");for(int i=0;i<3;i++)if(source[i].diffuseTexture!=sourceDiff[i]||source[i].normalMapTexture!=sourceNorm[i]||source[i].maskMapTexture!=sourceMask[i])throw new System.Exception("Source V3 layer changed.");
 string after;using(var sha=System.Security.Cryptography.SHA256.Create())after=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(scenePath))).Replace("-","");if(sceneHash!=after)throw new System.Exception("Scene file changed during Play Mode.");if(errors.Count>0)throw new System.Exception("Console errors: "+string.Join(" | ",errors.ToArray()));
 string r="{\"passed\":true,\"scene\":\""+scenePath+"\",\"initial\":\"V3B\",\"sequence\":\"F7,F8,F7,F8,W,F6,F7,disable,re-enable\",\"frames\":"+frames+",\"playerDeltaM\":"+moveDelta.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\"cameraDeltaM\":"+cameraDelta.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\"sourceHeightAndAlphamapsUnchanged\":true,\"sourceV3LayersUnchanged\":true,\"disableRestoredSourceAndDestroyedCopies\":true,\"reenableFreshCopiesDefaultB\":true,\"sceneHashUnchanged\":true,\"consoleErrors\":"+errors.Count+"}";System.IO.File.WriteAllText("Artifacts/TerrainRoadV4_1/TerrainRoadV4_PlayerLoopProbe.json",r,new System.Text.UTF8Encoding(false));UnityEngine.Debug.Log("RoadV4 probe passed: "+r);
 } finally{UnityEngine.Application.logMessageReceived-=log;try{UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());UnityEngine.InputSystem.InputSystem.RemoveDevice(keyboard);}catch{}player.transform.position=playerPos;player.transform.rotation=playerRot;camera.transform.localRotation=cameraLocalRot;UnityEngine.Physics.SyncTransforms();if(focus!=null)focus.Focus();}
 }
 movement.StartCoroutine(Probe());System.IO.File.WriteAllText("Artifacts/TerrainRoadV4_1/TerrainRoadV4_PlayerLoopProbe.json","{\"status\":\"running\"}",new System.Text.UTF8Encoding(false));
 bool HeightsSame(float[,] a,float[,] b){if(a.GetLength(0)!=b.GetLength(0)||a.GetLength(1)!=b.GetLength(1))return false;for(int y=0;y<a.GetLength(0);y++)for(int x=0;x<a.GetLength(1);x++)if(System.Math.Abs(a[y,x]-b[y,x])>1e-6f)return false;return true;}
 bool AlphasSame(float[,,] a,float[,,] b){if(a.GetLength(0)!=b.GetLength(0)||a.GetLength(1)!=b.GetLength(1)||a.GetLength(2)!=b.GetLength(2))return false;for(int y=0;y<a.GetLength(0);y++)for(int x=0;x<a.GetLength(1);x++)for(int l=0;l<a.GetLength(2);l++)if(System.Math.Abs(a[y,x,l]-b[y,x,l])>1e-6f)return false;return true;}
}))();

