((System.Action)(() => {
// Disposable, unsaved Terrain diagnostic for vertical mask/context alignment.
const string output="Artifacts/TerrainRoadReliefV2/batch3b_orientation_probe.json";
var mask=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Texture2D>("Assets/Art/Environment/TerrainRoadLookdev/SurfaceV2/RoadLimit_ReliefV2.png");
var layers=new UnityEngine.TerrainLayer[] {
 UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainLayer>("Assets/Art/Environment/TerrainRoadLookdev/TerrainLayers/TL_Grass_Warm.terrainlayer"),
 UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainLayer>("Assets/Art/Environment/TerrainRoadLookdev/TerrainLayers/TL_Road_ReliefV2.terrainlayer"),
 UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainLayer>("Assets/Art/Environment/TerrainRoadLookdev/TerrainLayers/TL_Stone_Grey_ReliefV2.terrainlayer"),
 UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainLayer>("Assets/Art/Environment/TerrainRoadLookdev/TerrainLayers/TL_Earth_Dark_ReliefV2.terrainlayer")};
if(!mask||!mask.isReadable||layers.Any(x=>!x))throw new System.Exception("Diagnostic mask/layers missing.");
UnityEngine.TerrainData d=new UnityEngine.TerrainData();d.heightmapResolution=257;d.alphamapResolution=256;d.baseMapResolution=256;d.size=new UnityEngine.Vector3(32f,4f,32f);d.terrainLayers=layers;
float[,] h=new float[257,257];for(int y=0;y<257;y++)for(int x=0;x<257;x++)h[y,x]=.5f;d.SetHeights(0,0,h);
float[,,] a=new float[256,256,4];for(int y=0;y<256;y++)for(int x=0;x<256;x++)a[y,x,0]=1f;d.SetAlphamaps(0,0,a);
var preview=UnityEditor.SceneManagement.EditorSceneManager.NewPreviewScene();UnityEngine.GameObject go=null;var window=UnityEditor.EditorWindow.GetWindow<RageQuitting.EditorTools.TerrainRoadLookdev.TerrainRoadReliefBrush>("Road Relief");var type=typeof(RageQuitting.EditorTools.TerrainRoadLookdev.TerrainRoadReliefBrush);void Set(string n,object v)=>type.GetField(n,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(window,v);
var center=new UnityEngine.Vector2(17.999f,19.299f);float roadCenter=mask.GetPixelBilinear(center.x/32f,center.y/32f).r;float mirroredRoad=mask.GetPixelBilinear(center.x/32f,(32f-center.y)/32f).r;
try {
 go=new UnityEngine.GameObject("__Batch3B_OrientationProbe");UnityEditor.SceneManagement.EditorSceneManager.MoveGameObjectToScene(go,preview);var t=go.AddComponent<UnityEngine.Terrain>();t.terrainData=d;var tc=go.AddComponent<UnityEngine.TerrainCollider>();tc.terrainData=d;
 Set("targetTerrain",t);Set("stoneLayer",layers[2]);Set("darkEarthLayer",layers[3]);Set("roadLimitMask",mask);Set("surfaceKind",System.Enum.ToObject(type.GetNestedType("SurfaceKind",System.Reflection.BindingFlags.NonPublic),0));Set("stampIndex",1);Set("paintingEnabled",true);Set("brushSize",1.38f);Set("strength",.9f);Set("rotationDegrees",296f);Set("scaleJitter",0f);Set("randomRotation",false);Set("stoneLift",new UnityEngine.Vector2(.038f,.038f));Set("random",new System.Random(431));
 type.GetMethod("BeginStroke",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(window,new object[]{new UnityEngine.Vector3(center.x,0,center.y)});type.GetMethod("EndStroke",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(window,null);
 float[,] after=d.GetHeights(0,0,257,257);float[,,] aa=d.GetAlphamaps(0,0,256,256);float outH=0,inH=0,outA=0,inA=0;int outHx=-1,outHy=-1,outAx=-1,outAy=-1;
 for(int y=0;y<257;y++)for(int x=0;x<257;x++){float wx=x/256f*32f,wz=y/256f*32f,m=mask.GetPixelBilinear(wx/32f,wz/32f).r,delta=(after[y,x]-.5f)*4f;if(m<.5f&&Mathf.Abs(delta)>outH){outH=Mathf.Abs(delta);outHx=x;outHy=y;}if(m>=.5f)inH=Mathf.Max(inH,Mathf.Abs(delta));}
 for(int y=0;y<256;y++)for(int x=0;x<256;x++){float wx=(x+.5f)/256f*32f,wz=(y+.5f)/256f*32f,m=mask.GetPixelBilinear(wx/32f,wz/32f).r,delta=aa[y,x,2];if(m<.5f&&delta>outA){outA=delta;outAx=x;outAy=y;}if(m>=.5f)inA=Mathf.Max(inA,delta);}
 float centerH=(after[Mathf.RoundToInt(center.y/32f*256),Mathf.RoundToInt(center.x/32f*256)]-.5f)*4f;int chx=Mathf.RoundToInt(center.x/32f*256),chy=Mathf.RoundToInt(center.y/32f*256);float centerW=aa[Mathf.Clamp((int)(center.y/32f*256),0,255),Mathf.Clamp((int)(center.x/32f*256),0,255),2];
 string json="{\n\"passedNoMaskSpill\":"+(outH<1e-6f&&outA<.005f?"true":"false")+",\n\"center\":["+center.x+","+center.y+"],\n\"centerRoadMask\":"+roadCenter.ToString("G6",System.Globalization.CultureInfo.InvariantCulture)+",\n\"mirroredRoadMask\":"+mirroredRoad.ToString("G6",System.Globalization.CultureInfo.InvariantCulture)+",\n\"maxInsideHeightDeltaM\":"+inH.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"maxOutsideHeightDeltaM\":"+outH.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"maxInsideStoneWeight\":"+inA.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"maxOutsideStoneWeight\":"+outA.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"outsideHeightIndex\":["+outHx+","+outHy+"],\n\"outsideAlphaIndex\":["+outAx+","+outAy+"],\n\"centerMeasuredHeightDeltaM\":"+centerH.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"centerStoneWeight\":"+centerW.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+"\n}\n";
 System.IO.File.WriteAllText(output,json,new System.Text.UTF8Encoding(false));Debug.Log("Batch3B disposable orientation probe: "+json);
} finally { if(window)UnityEngine.Object.DestroyImmediate(window); if(go)UnityEngine.Object.DestroyImmediate(go);if(d)UnityEngine.Object.DestroyImmediate(d);UnityEditor.SceneManagement.EditorSceneManager.ClosePreviewScene(preview); }
}))();
