((System.Action)(() => {
var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(scene.path!="Assets/Scenes/TerrainRoad_Lookdev.unity")throw new System.Exception("Unexpected active scene.");
var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>();var tc=terrain?terrain.GetComponent<UnityEngine.TerrainCollider>():null;var player=UnityEngine.GameObject.Find("PlayerNew");var controller=player?player.GetComponentInChildren<UnityEngine.CharacterController>(true):null;var cam=UnityEngine.Camera.main;
string PathOf(UnityEngine.Transform t){var p=new System.Collections.Generic.List<string>();while(t){p.Insert(0,t.name);t=t.parent;}return string.Join("/",p);}
var rows=new System.Collections.Generic.List<string>();if(player){rows.Add("PLAYER|"+PathOf(player.transform)+"|active="+player.activeInHierarchy+"|worldPos="+player.transform.position.ToString("F4")+"|worldRot="+player.transform.rotation.eulerAngles.ToString("F3"));foreach(var c in player.GetComponentsInChildren<UnityEngine.Component>(true)){if(!c)continue;var extra="";if(c is UnityEngine.CharacterController cc)extra="|enabled="+cc.enabled+"|height="+cc.height+"|radius="+cc.radius+"|center="+cc.center+"|slope="+cc.slopeLimit+"|step="+cc.stepOffset+"|grounded="+cc.isGrounded; if(c is UnityEngine.Camera camera)extra="|enabled="+camera.enabled+"|tag="+camera.tag+"|depth="+camera.depth;rows.Add("COMP|"+PathOf(c.transform)+"|"+c.GetType().FullName+extra);}}
foreach(var c in UnityEngine.Object.FindObjectsByType<UnityEngine.Camera>(UnityEngine.FindObjectsSortMode.None))rows.Add("CAM|"+PathOf(c.transform)+"|active="+c.isActiveAndEnabled+"|tag="+c.tag+"|main="+(c==cam));
string hash;using(var sha=System.Security.Cryptography.SHA256.Create())hash=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(scene.path))).Replace("-","");
string head="scene="+scene.path+"|dirty="+scene.isDirty+"|playing="+UnityEditor.EditorApplication.isPlaying+"|playerFound="+(player!=null)+"|controllerFound="+(controller!=null)+"|terrain="+(terrain?UnityEditor.AssetDatabase.GetAssetPath(terrain.terrainData):"null")+"|terrainCollider="+(tc?UnityEditor.AssetDatabase.GetAssetPath(tc.terrainData):"null")+"|terrainColliderEnabled="+(tc?tc.enabled:false)+"|drawHeightmap="+(terrain?terrain.drawHeightmap:false)+"|cameraMain="+(cam?PathOf(cam.transform):"null")+"|sceneFileHash="+hash;
System.IO.File.WriteAllText("Artifacts/TerrainRoadReliefV2/batch4a_scene_setup.txt",head+"\n"+string.Join("\n",rows),new System.Text.UTF8Encoding(false));Debug.Log("Batch4A scene setup: "+head);
}))();
