((System.Action)(() => {
// Disposable one-texel PaintContext probe. Mirrors the brush's ReadPixels + SetPixels + Graphics.Blit path.
const string report="Artifacts/TerrainRoadReliefV2/batch3b_context_mapping_probe.json";
var preview=UnityEditor.SceneManagement.EditorSceneManager.NewPreviewScene();UnityEngine.GameObject go=null;UnityEngine.TerrainData d=null;
try {
 d=new UnityEngine.TerrainData();d.heightmapResolution=257;d.alphamapResolution=256;d.baseMapResolution=256;d.size=new UnityEngine.Vector3(32,4,32);go=new UnityEngine.GameObject("__Batch3B_ContextMappingProbe");UnityEditor.SceneManagement.EditorSceneManager.MoveGameObjectToScene(go,preview);var t=go.AddComponent<UnityEngine.Terrain>();t.terrainData=d;var tc=go.AddComponent<UnityEngine.TerrainCollider>();tc.terrainData=d;
 float[,] before=new float[257,257];for(int y=0;y<257;y++)for(int x=0;x<257;x++)before[y,x]=.5f;d.SetHeights(0,0,before);
 var center=new UnityEngine.Vector3(17.999f,0,19.299f);float size=1.38f;var r=new UnityEngine.Rect(center.x-size*.85f,center.z-size*.85f,size*1.7f,size*1.7f);var c=UnityEngine.TerrainTools.TerrainPaintUtility.BeginPaintHeightmap(t,r,0,false);
 string rectText=c.pixelRect.ToString();int targetW=c.targetTextureWidth,targetH=c.targetTextureHeight;int gx=148,gy=153,lx=gx-c.pixelRect.x,ly=gy-c.pixelRect.y;var source=c.sourceRenderTexture;
 UnityEngine.RenderTexture old=UnityEngine.RenderTexture.active;var read=new UnityEngine.Texture2D(source.width,source.height,UnityEngine.TextureFormat.RGBAFloat,false,true);UnityEngine.RenderTexture.active=source;read.ReadPixels(new UnityEngine.Rect(0,0,source.width,source.height),0,0,false);read.Apply(false,false);var colors=read.GetPixels();UnityEngine.Color beforeTexel=colors[ly*source.width+lx];colors[ly*source.width+lx]=new UnityEngine.Color(beforeTexel.r+.01f,beforeTexel.g,beforeTexel.b,beforeTexel.a);
 var upload=new UnityEngine.Texture2D(source.width,source.height,UnityEngine.TextureFormat.RGBAFloat,false,true);upload.SetPixels(colors);upload.Apply(false,false);UnityEngine.Graphics.Blit(upload,c.destinationRenderTexture);UnityEngine.RenderTexture.active=old;UnityEngine.TerrainTools.TerrainPaintUtility.EndPaintHeightmap(c,"Batch3B one-pixel diagnostic");
 float[,] after=d.GetHeights(0,0,257,257);var changed=new System.Collections.Generic.List<string>();float max=0;int maxX=-1,maxY=-1;for(int y=0;y<257;y++)for(int x=0;x<257;x++){float diff=after[y,x]-before[y,x];if(UnityEngine.Mathf.Abs(diff)>1e-6f)changed.Add("["+x+","+y+"]="+diff.ToString("G6",System.Globalization.CultureInfo.InvariantCulture));if(UnityEngine.Mathf.Abs(diff)>max){max=UnityEngine.Mathf.Abs(diff);maxX=x;maxY=y;}}
 string json="{\n\"rect\":\""+rectText+"\",\n\"targetTexture\":["+targetW+","+targetH+"],\n\"rt\":["+source.width+","+source.height+"],\n\"writtenLocal\":["+lx+","+ly+"],\n\"writtenGlobalIntent\":["+gx+","+gy+"],\n\"sourceTexelBeforeR\":"+beforeTexel.r.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"changedHeightSamples\":"+changed.Count+",\n\"maxChangedAt\":["+maxX+","+maxY+"],\n\"maxNormalizedDelta\":"+max.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n\"changed\":["+string.Join(",",changed)+"]\n}\n";System.IO.File.WriteAllText(report,json,new System.Text.UTF8Encoding(false));UnityEngine.Object.DestroyImmediate(read);UnityEngine.Object.DestroyImmediate(upload);
} finally {if(go)UnityEngine.Object.DestroyImmediate(go);if(d)UnityEngine.Object.DestroyImmediate(d);UnityEditor.SceneManagement.EditorSceneManager.ClosePreviewScene(preview);}
}))();
