((System.Action)(() => {
if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Not in Play Mode.");
var p=UnityEngine.GameObject.Find("PlayerNew");var m=p? p.GetComponent<StarterAssets.FirstPersonController>():null;var input=p?p.GetComponent<PlayerInputNew>():null;var cam=UnityEngine.Camera.main;
if(!p||!m||!m.enabled||!input||!cam)throw new System.Exception("Player/controller/input/camera missing.");
var kb=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Keyboard>("B4VirtualKeyboard");int f=0,errs=0;UnityEngine.Vector3 p0=UnityEngine.Vector3.zero,c0=UnityEngine.Vector3.zero,p1=p0,c1=c0;UnityEngine.Vector2 v0=UnityEngine.Vector2.zero,v1=v0;
UnityEngine.Application.LogCallback log=(a,b,k)=>{if(k==UnityEngine.LogType.Error||k==UnityEngine.LogType.Exception||k==UnityEngine.LogType.Assert)errs++;};UnityEngine.Application.logMessageReceived+=log;
UnityEditor.EditorApplication.CallbackFunction tick=null;System.Action clean=()=>{UnityEditor.EditorApplication.update-=tick;UnityEngine.Application.logMessageReceived-=log;if(kb!=null){try{UnityEngine.InputSystem.InputSystem.QueueStateEvent(kb,new UnityEngine.InputSystem.LowLevel.KeyboardState());UnityEngine.InputSystem.InputSystem.RemoveDevice(kb);}catch{}}};
tick=()=>{try{f++;if(f==3){p0=p.transform.position;c0=cam.transform.position;UnityEngine.InputSystem.InputSystem.QueueStateEvent(kb,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.W));}if(f==10)v0=input.GetMoveVectorValue();if(f==24)v1=input.GetMoveVectorValue();if(f==26)UnityEngine.InputSystem.InputSystem.QueueStateEvent(kb,new UnityEngine.InputSystem.LowLevel.KeyboardState());if(f>=32){p1=p.transform.position;c1=cam.transform.position;float pd=UnityEngine.Vector3.Distance(p0,p1),cd=UnityEngine.Vector3.Distance(c0,c1);bool ok=v0.y>.5f&&v1.y>.5f&&pd>.1f&&cd>.01f&&errs==0;System.IO.File.WriteAllText("Artifacts/TerrainRoadReliefV2/batch4a_input_probe.txt","passed="+ok+"|frames="+f+"|moveSamples="+v0.ToString("F2")+","+v1.ToString("F2")+"|playerDeltaM="+pd.ToString("F4")+"|cameraDeltaM="+cd.ToString("F4")+"|consoleErrors="+errs+"|controllerEnabled="+m.enabled+"|deviceRemoved=true\\n");clean();if(!ok)UnityEngine.Debug.LogError("Batch4A synthetic W input probe failed.");else UnityEngine.Debug.Log("Batch4A synthetic W input probe passed; player="+pd.ToString("F3")+"m camera="+cd.ToString("F3")+"m.");}}catch(System.Exception e){System.IO.File.WriteAllText("Artifacts/TerrainRoadReliefV2/batch4a_input_probe.txt","passed=false|error="+e.Message+"|frame="+f+"\\n");clean();UnityEngine.Debug.LogException(e);}};
UnityEditor.EditorApplication.update+=tick;System.IO.File.WriteAllText("Artifacts/TerrainRoadReliefV2/batch4a_input_probe_started.txt","scheduled\\n");Debug.Log("Batch4A W input probe scheduled.");
}))();

