((System.Action)(() => {
const string targetScene="Assets/Scenes/TerrainRoad_Lookdev.unity", tdPath="Assets/Art/Environment/TerrainRoadLookdev/TerrainData/TD_TerrainRoad_ReliefV3.asset";
const string output="Artifacts/TerrainRoadV3/TerrainRoadV3_SyntheticTraversal.json";
if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Road traversal must run in Play Mode.");var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(scene.path!=targetScene)throw new System.Exception("Wrong active scene.");
var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>();var tc=terrain?terrain.GetComponent<UnityEngine.TerrainCollider>():null;var d=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainData>(tdPath);var player=UnityEngine.GameObject.Find("PlayerNew");var cc=player?player.GetComponent<UnityEngine.CharacterController>():null;var camera=UnityEngine.Camera.main;var movement=player?player.GetComponent("FirstPersonController") as UnityEngine.Behaviour:null;var switcher=terrain?terrain.GetComponent("TerrainRoadV3RuntimeSwitcher"):null;var runtimeData=switcher==null?null:switcher.GetType().GetProperty("RuntimeData").GetValue(switcher,null) as UnityEngine.TerrainData;
if(!terrain||!tc||!d||runtimeData==null||tc.terrainData!=runtimeData||terrain.terrainData!=runtimeData||!tc.enabled||!terrain.drawHeightmap||!player||!cc||!camera||!camera.isActiveAndEnabled)throw new System.Exception("Runtime Player/Camera/Terrain/TerrainCollider/V3 clone precondition failed.");
string sceneHash;using(var sha=System.Security.Cryptography.SHA256.Create())sceneHash=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(targetScene))).Replace("-","");
var path=new UnityEngine.Vector2[]{new UnityEngine.Vector2(14f,3f),new UnityEngine.Vector2(14.4f,6.5f),new UnityEngine.Vector2(15.5f,10f),new UnityEngine.Vector2(17f,13f),new UnityEngine.Vector2(17.6f,16.8f),new UnityEngine.Vector2(17.1f,20f),new UnityEngine.Vector2(16.3f,24f),new UnityEngine.Vector2(16f,28f)};
var errors=new System.Collections.Generic.List<string>();UnityEngine.Application.LogCallback handler=(condition,stack,kind)=>{if(kind==UnityEngine.LogType.Error||kind==UnityEngine.LogType.Exception||kind==UnityEngine.LogType.Assert)errors.Add(kind+":"+condition);};UnityEngine.Application.logMessageReceived+=handler;
bool originalCc=cc.enabled,originalMovement=movement?movement.enabled:false;var originalPlayer=player.transform.position;float distance=0f,maxDeviation=0f,maxVerticalGap=0f;int blocked=0,rayHits=0,steps=0;
try {
if(movement)movement.enabled=false;
Vector3 LocalToWorld(UnityEngine.Vector2 p){return terrain.transform.TransformPoint(new UnityEngine.Vector3(p.x,0f,p.y));}
for(int i=0;i<path.Length;i++){Vector3 p=LocalToWorld(path[i]);Vector3 rayOrigin=new UnityEngine.Vector3(p.x,terrain.transform.position.y+d.size.y+10f,p.z);UnityEngine.RaycastHit hit;if(tc.Raycast(new UnityEngine.Ray(rayOrigin,UnityEngine.Vector3.down),out hit,100f))rayHits++;else throw new System.Exception("TerrainCollider vertical ray missed waypoint "+i);if(i>0)distance+=UnityEngine.Vector2.Distance(path[i-1],path[i]);}
cc.enabled=false;Vector3 start=LocalToWorld(path[0]);float ground=terrain.SampleHeight(start)+terrain.transform.position.y;player.transform.position=new UnityEngine.Vector3(start.x,ground-cc.center.y+cc.height*.5f+.015f,start.z);cc.enabled=originalCc;UnityEngine.Physics.SyncTransforms();
const float stepDistance=.18f;
for(int i=1;i<path.Length;i++){Vector3 a=LocalToWorld(path[i-1]),b=LocalToWorld(path[i]);float segment=UnityEngine.Vector2.Distance(new UnityEngine.Vector2(a.x,a.z),new UnityEngine.Vector2(b.x,b.z));int count=UnityEngine.Mathf.Max(1,UnityEngine.Mathf.CeilToInt(segment/stepDistance));
for(int k=1;k<=count;k++){Vector3 target=UnityEngine.Vector3.Lerp(a,b,k/(float)count);float targetGround=terrain.SampleHeight(target)+terrain.transform.position.y;float targetRootY=targetGround-cc.center.y+cc.height*.5f+.015f;Vector3 before=player.transform.position;var flags=cc.Move(new UnityEngine.Vector3(target.x-before.x,targetRootY-before.y,target.z-before.z));Vector3 after=player.transform.position;steps++;if((flags&UnityEngine.CollisionFlags.Sides)!=0)blocked++;float error=UnityEngine.Vector2.Distance(new UnityEngine.Vector2(after.x-target.x,after.z-target.z),UnityEngine.Vector2.zero);maxDeviation=UnityEngine.Mathf.Max(maxDeviation,error);float foot=after.y+cc.center.y-cc.height*.5f;maxVerticalGap=UnityEngine.Mathf.Max(maxVerticalGap,UnityEngine.Mathf.Abs(foot-targetGround));}}
float startZ=LocalToWorld(path[0]).z,finishZ=LocalToWorld(path[path.Length-1]).z;float movedZ=player.transform.position.z-startZ;
if(steps<100||rayHits!=path.Length||maxDeviation>.15f||maxVerticalGap>.12f||UnityEngine.Mathf.Abs(movedZ-(finishZ-startZ))>.25f)throw new System.Exception("Traversal failed: steps="+steps+", rayHits="+rayHits+", deviation="+maxDeviation+", verticalGap="+maxVerticalGap+", movedZ="+movedZ+".");
string hashAfter;using(var sha=System.Security.Cryptography.SHA256.Create())hashAfter=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(targetScene))).Replace("-","");if(hashAfter!=sceneHash)throw new System.Exception("Target scene file changed during Play Mode test.");
string result="{\n  \"passed\":true,\n  \"mode\":\"Unity Play Mode, single-player scene; synthetic CharacterController.Move traversal (not WASD input walk)\",\n  \"scene\":\""+scene.path+"\",\n  \"player\":\"PlayerNew\",\n  \"movementController\":\"StarterAssets.FirstPersonController disabled temporarily during direct controlled Move calls\",\n  \"mainCamera\":\""+camera.name+"\",\n  \"terrainDataPath\":\""+tdPath+" (runtime clone: "+runtimeData.name+")"+"\",\n  \"terrainColliderDataPath\":\""+tdPath+" (runtime clone: "+runtimeData.name+")"+"\",\n  \"terrainColliderEnabled\":true,\n  \"terrainVisible\":"+(terrain.drawHeightmap?"true":"false")+",\n  \"roadLengthM\":"+distance.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"steps\":"+steps+",\n  \"terrainColliderWaypointRayHits\":"+rayHits+",\n  \"waypointCount\":"+path.Length+",\n  \"sideCollisionFlags\":"+blocked+",\n  \"maxHorizontalPathDeviationM\":"+maxDeviation.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"maxFootToTerrainGapM\":"+maxVerticalGap.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"zStartM\":"+startZ.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"zFinishM\":"+finishZ.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"consoleErrorsDuringTraversal\":"+errors.Count+",\n  \"sceneHashUnchanged\":"+(hashAfter==sceneHash?"true":"false")+"\n}\n";
System.IO.File.WriteAllText(output,result,new System.Text.UTF8Encoding(false));
} catch(System.Exception e){System.IO.File.WriteAllText(output,"{\"passed\":false,\"error\":\""+e.Message.Replace("\\","\\\\").Replace("\"","\\\"")+"\",\"steps\":"+steps+",\"maxHorizontalPathDeviationM\":"+maxDeviation.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\"maxFootToTerrainGapM\":"+maxVerticalGap.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\"consoleErrors\":"+errors.Count+"}\n",new System.Text.UTF8Encoding(false));throw;}finally{cc.enabled=false;player.transform.position=originalPlayer;UnityEngine.Physics.SyncTransforms();cc.enabled=originalCc;if(movement)movement.enabled=originalMovement;UnityEngine.Application.logMessageReceived-=handler;}
Debug.Log("TerrainRoadV3 synthetic road traversal passed; report="+output+"; steps="+steps+"; deviation="+maxDeviation+".");
}))();
