if(UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Capture requires Edit Mode.");
var view=UnityEditor.SceneView.lastActiveSceneView;if(view==null||view.camera==null)throw new System.Exception("No active SceneView camera.");
var cam=view.camera;var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>();if(terrain==null)throw new System.Exception("Active Terrain missing.");
var oldPivot=view.pivot;var oldRotation=view.rotation;float oldSize=view.size;bool oldOrtho=view.orthographic;var oldPosition=cam.transform.position;var oldCameraRotation=cam.transform.rotation;var oldTarget=cam.targetTexture;var oldActive=UnityEngine.RenderTexture.active;
const int width=1600,height=900;var rt=new UnityEngine.RenderTexture(width,height,24,UnityEngine.RenderTextureFormat.ARGB32);var image=new UnityEngine.Texture2D(width,height,UnityEngine.TextureFormat.RGB24,false);
var cameraPosition=new UnityEngine.Vector3(17.35f,0,13.35f);cameraPosition.y=terrain.SampleHeight(cameraPosition+UnityEngine.Vector3.up*20f)+terrain.transform.position.y+1.65f;
var focus=new UnityEngine.Vector3(19.35f,0,13.85f);focus.y=terrain.SampleHeight(focus+UnityEngine.Vector3.up*20f)+terrain.transform.position.y+0.28f;
var cameraRotation=UnityEngine.Quaternion.LookRotation(focus-cameraPosition,UnityEngine.Vector3.up);
try{
 cam.transform.SetPositionAndRotation(cameraPosition,cameraRotation);cam.targetTexture=rt;UnityEngine.RenderTexture.active=rt;cam.Render();image.ReadPixels(new UnityEngine.Rect(0,0,width,height),0,0);image.Apply();
 var path="D:/Programy/UnityProjects/RageQuitting/Artifacts/RoadsideV1/RoadsideV1_SceneQA_PlayerLevel.png";System.IO.File.WriteAllBytes(path,image.EncodeToPNG());
 var record="{\"view\":\"playerLevel\",\"scene\":\""+scene.path+"\",\"cameraPosition\":["+cameraPosition.x.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+cameraPosition.y.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+cameraPosition.z.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+"],\"cameraRotation\":["+cameraRotation.x.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+cameraRotation.y.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+cameraRotation.z.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+cameraRotation.w.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+"],\"focus\":["+focus.x.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+focus.y.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+","+focus.z.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+"],\"heightAboveTerrainMeters\":1.65}";
 System.IO.File.WriteAllText("D:/Programy/UnityProjects/RageQuitting/Artifacts/RoadsideV1/RoadsideV1_SceneQA_PlayerLevelCamera.json",record);
}finally{UnityEngine.RenderTexture.active=oldActive;cam.targetTexture=oldTarget;cam.transform.SetPositionAndRotation(oldPosition,oldCameraRotation);view.pivot=oldPivot;view.rotation=oldRotation;view.size=oldSize;view.orthographic=oldOrtho;UnityEngine.Object.DestroyImmediate(image);rt.Release();UnityEngine.Object.DestroyImmediate(rt);view.Repaint();}
return "Artifacts/RoadsideV1/RoadsideV1_SceneQA_PlayerLevel.png (1600x900); explicit camera position="+cameraPosition+"; height=1.65m above Terrain; prior camera/SceneView/render target restored";
