var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();
if(scene.path!="Assets/Scenes/TerrainRoad_Lookdev.unity"||UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Validation requires target scene in Edit Mode.");
var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>();var collider=terrain?terrain.GetComponent<UnityEngine.TerrainCollider>():null;
var original=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainData>("Assets/Art/Environment/TerrainRoadLookdev/TerrainData/TD_TerrainRoad_ReliefV3.asset");var data=terrain?terrain.terrainData:null;
if(terrain==null||collider==null||original==null||data==null)throw new System.Exception("Terrain precondition missing.");
var root=UnityEngine.GameObject.Find("Roadside_V1");if(root==null)throw new System.Exception("Roadside_V1 root missing.");
double[] px={14,14.4,15.5,17,17.6,17.1,16.3,16},pz={3,6.5,10,13,16.8,20,24,28};
double Smooth(double a,double b,double v){double t=System.Math.Max(0,System.Math.Min(1,(v-a)/(b-a)));return t*t*(3-2*t);}
double Dist(double x,double z){double best=1e9;for(int i=0;i<px.Length-1;i++){double dx=px[i+1]-px[i],dz=pz[i+1]-pz[i],q=((x-px[i])*dx+(z-pz[i])*dz)/(dx*dx+dz*dz);q=System.Math.Max(0,System.Math.Min(1,q));double ex=x-(px[i]+q*dx),ez=z-(pz[i]+q*dz);best=System.Math.Min(best,System.Math.Sqrt(ex*ex+ez*ez));}return best;}
var heights=original.GetHeights(0,0,original.heightmapResolution,original.heightmapResolution);var clonedHeights=data.GetHeights(0,0,data.heightmapResolution,data.heightmapResolution);double maxHeightDelta=0;
for(int z=0;z<heights.GetLength(0);z++)for(int x=0;x<heights.GetLength(1);x++)maxHeightDelta=System.Math.Max(maxHeightDelta,System.Math.Abs(heights[z,x]-clonedHeights[z,x]));
var baseAlpha=original.GetAlphamaps(0,0,original.alphamapWidth,original.alphamapHeight);var alpha=data.GetAlphamaps(0,0,data.alphamapWidth,data.alphamapHeight);double maxOutsideDelta=0,maxLaneDelta=0,weightSumError=0;int changedCells=0,outsideChanged=0,laneChanged=0,maskedCells=0;
for(int z=0;z<alpha.GetLength(0);z++)for(int x=0;x<alpha.GetLength(1);x++){
 double wx=((double)x+0.5)/data.alphamapWidth*data.size.x+terrain.transform.position.x,wz=((double)z+0.5)/data.alphamapHeight*data.size.z+terrain.transform.position.z,d=Dist(wx,wz),zone=Smooth(9,9.7,wz)*(1-Smooth(18.3,19,wz)),wave=0.5+0.5*System.Math.Sin(wx*0.71+System.Math.Sin(wz*0.39)*1.6)*System.Math.Cos(wz*0.53-wx*0.17),outer=1.92+wave*0.12,edge=Smooth(1.28,1.48,d)*(1-Smooth(outer-0.18,outer,d)),expectedMask=zone*edge*0.72>0.0005?1:0;
 bool changed=false;double sum=0;for(int l=0;l<4;l++){sum+=alpha[z,x,l];double delta=System.Math.Abs(alpha[z,x,l]-baseAlpha[z,x,l]);if(delta>1e-6)changed=true;if(expectedMask==0)maxOutsideDelta=System.Math.Max(maxOutsideDelta,delta);if(d<1.0)maxLaneDelta=System.Math.Max(maxLaneDelta,delta);}
 weightSumError=System.Math.Max(weightSumError,System.Math.Abs(sum-1));if(changed)changedCells++;if(expectedMask==0&&changed)outsideChanged++;if(d<1.0&&changed)laneChanged++;if(expectedMask>0)maskedCells++;
}
var expectedGrass=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainLayer>("Assets/Art/Environment/TerrainRoadLookdev/RoadsideV1/TerrainData/TL_RoadsideV1_Grass.terrainlayer");bool layerRefs=data.terrainLayers.Length==4&&data.terrainLayers[0]==expectedGrass;for(int i=1;i<4&&layerRefs;i++)layerRefs=data.terrainLayers[i]==original.terrainLayers[i];
var expectedGrassMat=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Material>("Assets/Art/Environment/TerrainRoadLookdev/RoadsideV1/Materials/M_RoadsideV1_Grass.mat");var expectedRockMat=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Material>("Assets/Art/Environment/TerrainRoadLookdev/RoadsideV1/Materials/M_RoadsideV1_Rock.mat");
int grassCount=0,rockCount=0,colliders=0,rigidbodies=0,wrongMaterials=0,wrongShadow=0,rootsOutOfZone=0;double minRouteClearance=1e9,maxGrassBaseAbove=double.NegativeInfinity,minGrassVisible=1e9,minRockVisible=1e9,minRockEmbed=1e9,maxRockEmbed=0;float minRootZ=1e9f,maxRootZ=-1e9f;
foreach(var tr in root.GetComponentsInChildren<UnityEngine.Transform>(true)){
 var go=tr.gameObject;if(go==root||go.name=="GrassClumps"||go.name=="Rocks")continue;bool grass=go.name.StartsWith("Grass_"),rock=go.name.StartsWith("Rock_");if(!grass&&!rock)continue;
 if(grass)grassCount++;else rockCount++;if(tr.position.z<9||tr.position.z>19)rootsOutOfZone++;minRootZ=System.Math.Min(minRootZ,tr.position.z);maxRootZ=System.Math.Max(maxRootZ,tr.position.z);
 if(go.GetComponentInChildren<UnityEngine.Collider>(true)!=null)colliders++;if(go.GetComponentInChildren<UnityEngine.Rigidbody>(true)!=null)rigidbodies++;
 float visible=float.NegativeInfinity,footAbove=float.NegativeInfinity,rockSurface=terrain.SampleHeight(new UnityEngine.Vector3(tr.position.x,terrain.transform.position.y+5,tr.position.z));
 foreach(var mf in go.GetComponentsInChildren<UnityEngine.MeshFilter>(true)){
  var verts=mf.sharedMesh.vertices;float low=float.PositiveInfinity;foreach(var v in verts)low=System.Math.Min(low,mf.transform.TransformPoint(v).y);
  foreach(var v in verts){var q=mf.transform.TransformPoint(v);double d=Dist(q.x,q.z);minRouteClearance=System.Math.Min(minRouteClearance,d);float surface=terrain.SampleHeight(new UnityEngine.Vector3(q.x,terrain.transform.position.y+5,q.z));visible=System.Math.Max(visible,q.y-surface);if(q.y<=low+0.0001f)footAbove=System.Math.Max(footAbove,q.y-surface);}
 }
 maxGrassBaseAbove=grass?System.Math.Max(maxGrassBaseAbove,footAbove):maxGrassBaseAbove;if(grass)minGrassVisible=System.Math.Min(minGrassVisible,visible);else{minRockVisible=System.Math.Min(minRockVisible,visible);float embed=rockSurface-tr.position.y;minRockEmbed=System.Math.Min(minRockEmbed,embed);maxRockEmbed=System.Math.Max(maxRockEmbed,embed);}
 foreach(var r in go.GetComponentsInChildren<UnityEngine.Renderer>(true)){var mat=r.sharedMaterial;if(mat!=(grass?expectedGrassMat:expectedRockMat))wrongMaterials++;if(r.shadowCastingMode!=UnityEngine.Rendering.ShadowCastingMode.On||!r.receiveShadows)wrongShadow++;}
}
int activeLegacy=0,disabledLegacy=0;foreach(var go in UnityEngine.Object.FindObjectsByType<UnityEngine.GameObject>(UnityEngine.FindObjectsInactive.Include,UnityEngine.FindObjectsSortMode.None)){if(go.scene!=scene)continue;var p=go.transform.position;bool target=(go.name=="SM_RoadsideRock_02_Instance"&&System.Math.Abs(p.x-19.6)<0.06&&System.Math.Abs(p.z-13.7)<0.06)||(go.name=="SM_RoadsideGrass_02_Instance"&&System.Math.Abs(p.x-20.3)<0.06&&System.Math.Abs(p.z-13.9)<0.06)||(go.name=="SM_RoadsideGrass_01_Instance"&&System.Math.Abs(p.x-14.7)<0.06&&System.Math.Abs(p.z-16.2)<0.06)||((go.name=="SM_RoadsideGrassClusterExtra_0"||go.name=="SM_RoadsideGrassClusterExtra_1")&&System.Math.Abs(p.x-20.3)<0.06&&System.Math.Abs(p.z-13.9)<0.06);if(target){if(go.activeSelf)activeLegacy++;else disabledLegacy++;}}
var switcher=terrain.GetComponent("TerrainRoadV3RuntimeSwitcher");int switcherRoadLayers=0;var sourceField=switcher==null?null:switcher.GetType().GetField("sourceLayers",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var switchLayers=sourceField==null?null:sourceField.GetValue(switcher) as UnityEngine.TerrainLayer[];if(switchLayers!=null)switcherRoadLayers=switchLayers.Length;
int leakedRuntimeTerrainData=0,leakedRuntimeLayers=0;foreach(var item in UnityEngine.Resources.FindObjectsOfTypeAll<UnityEngine.TerrainData>())if(item!=data&&item.name.Contains("Road V3 Runtime"))leakedRuntimeTerrainData++;foreach(var item in UnityEngine.Resources.FindObjectsOfTypeAll<UnityEngine.TerrainLayer>())if(item!=null&&item.name.Contains("(Runtime)"))leakedRuntimeLayers++;
 var consoleType=typeof(UnityEditor.EditorWindow).Assembly.GetType("UnityEditor.LogEntries");var consoleMethod=consoleType==null?null:consoleType.GetMethod("GetCountsByType",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic);int consoleLogs=-1,consoleWarnings=-1,consoleErrors=-1;try{if(consoleMethod!=null){object[] args={0,0,0};consoleMethod.Invoke(null,args);consoleErrors=(int)args[0];consoleWarnings=(int)args[1];consoleLogs=(int)args[2];}}catch{}
string sceneHash;using(var sha=System.Security.Cryptography.SHA256.Create())sceneHash=System.BitConverter.ToString(sha.ComputeHash(System.IO.File.ReadAllBytes(scene.path))).Replace("-","");
var report="{\n  \"scene\":\""+scene.path+"\",\n  \"sceneSHA256\":\""+sceneHash+"\",\n  \"terrainData\":\""+UnityEditor.AssetDatabase.GetAssetPath(data)+"\",\n  \"colliderUsesSameData\":"+(collider.terrainData==data?"true":"false")+",\n  \"heightmapMaxAbsDelta\":"+maxHeightDelta.ToString("G9",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"fourLayerReferencesCorrect\":"+(layerRefs?"true":"false")+",\n  \"switcherRoadSourceLayerCount\":"+switcherRoadLayers+",\n  \"alphamapChangedCells\":"+changedCells+",\n  \"expectedPaintMaskCells\":"+maskedCells+",\n  \"changesOutsidePaintMask\":"+outsideChanged+",\n  \"maxOutsidePaintMaskWeightDelta\":"+maxOutsideDelta.ToString("G9",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"laneChangedCells_d_lt_1m\":"+laneChanged+",\n  \"maxLaneWeightDelta\":"+maxLaneDelta.ToString("G9",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"maxAlphamapWeightSumError\":"+weightSumError.ToString("G9",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"grassCount\":"+grassCount+",\n  \"rockCount\":"+rockCount+",\n  \"rootsOutsideZ9_19\":"+rootsOutOfZone+",\n  \"rootZRange\":["+minRootZ.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+","+maxRootZ.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+"],\n  \"minMeshVertexDistanceToRoadCenterlineM\":"+minRouteClearance.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"grassMaxFootVertexAboveTerrainM\":"+maxGrassBaseAbove.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"grassMinVisibleVertexAboveTerrainM\":"+minGrassVisible.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"rockMinVisibleVertexAboveTerrainM\":"+minRockVisible.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+",\n  \"rockRootEmbedDepthRangeM\":["+minRockEmbed.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+","+maxRockEmbed.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+"],\n  \"physicsComponents\":{\"colliders\":"+colliders+",\"rigidbodies\":"+rigidbodies+"},\n  \"wrongPrefabMaterials\":"+wrongMaterials+",\n  \"wrongShadowSettings\":"+wrongShadow+",\n  \"overlappingLegacy\":{\"active\":"+activeLegacy+",\"disabled\":"+disabledLegacy+"},\n  \"consoleCounts\":{\"logs\":"+consoleLogs+",\"warnings\":"+consoleWarnings+",\"errors\":"+consoleErrors+"}\n}\n";
report=report.Replace("  \"consoleCounts\"", "  \"runtimeCleanupAfterPlay\":{\"leakedTerrainDataClones\":"+leakedRuntimeTerrainData+",\"leakedTerrainLayerClones\":"+leakedRuntimeLayers+"},\n  \"sceneDirtyInEditMode\":"+(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene().isDirty?"true":"false")+",\n  \"consoleCounts\"");
var outputPath="Artifacts/RoadsideV1/SceneValidation.json";System.IO.File.WriteAllText(outputPath,report,new System.Text.UTF8Encoding(false));
if(maxHeightDelta!=0||!layerRefs||outsideChanged!=0||laneChanged!=0||weightSumError>0.0041||grassCount!=50||rockCount!=7||rootsOutOfZone!=0||minRouteClearance<1.0||maxGrassBaseAbove>0.01||minGrassVisible<0.045||minRockVisible<0.025||colliders!=0||rigidbodies!=0||wrongMaterials!=0||wrongShadow!=0||activeLegacy!=0||disabledLegacy!=5||leakedRuntimeTerrainData!=0||leakedRuntimeLayers!=0)throw new System.Exception("Roadside validation failed. Report: "+outputPath);
return outputPath+" passed; maxHeightDelta="+maxHeightDelta.ToString("G8",System.Globalization.CultureInfo.InvariantCulture)+"; changedCells="+changedCells+"; outside/lane changes=0; props=50+7; minClearance="+minRouteClearance.ToString("G6",System.Globalization.CultureInfo.InvariantCulture)+"; maxFootGap="+maxGrassBaseAbove.ToString("G6",System.Globalization.CultureInfo.InvariantCulture)+"; console="+consoleErrors+" errors/"+consoleWarnings+" warnings";
