if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Runtime re-entry check requires Play Mode.");
var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(scene.path!="Assets/Scenes/TerrainRoad_Lookdev.unity")throw new System.Exception("Wrong scene.");
var terrain=UnityEngine.Object.FindFirstObjectByType<UnityEngine.Terrain>();var collider=terrain?terrain.GetComponent<UnityEngine.TerrainCollider>():null;var root=UnityEngine.GameObject.Find("Roadside_V1");var player=UnityEngine.GameObject.Find("PlayerNew");var camera=UnityEngine.Camera.main;var switcher=terrain?terrain.GetComponent("TerrainRoadV3RuntimeSwitcher"):null;
var runtimeData=switcher==null?null:switcher.GetType().GetProperty("RuntimeData").GetValue(switcher,null) as UnityEngine.TerrainData;var isA=switcher==null?true:(bool)switcher.GetType().GetProperty("IsVariantA").GetValue(switcher,null);var persistent=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TerrainData>("Assets/Art/Environment/TerrainRoadLookdev/RoadsideV1/TerrainData/TD_TerrainRoad_RoadsideV1.asset");
if(terrain==null||collider==null||runtimeData==null||persistent==null||terrain.terrainData!=runtimeData||collider.terrainData!=runtimeData||runtimeData==persistent||isA||root==null||player==null||camera==null||!camera.isActiveAndEnabled)throw new System.Exception("Repeated Play runtime check failed: expected fresh shared runtime clone and default variant B.");
int grass=0,rocks=0;foreach(var t in root.GetComponentsInChildren<UnityEngine.Transform>(true)){if(t.name.StartsWith("Grass_"))grass++;if(t.name.StartsWith("Rock_"))rocks++;}
if(grass!=50||rocks!=7)throw new System.Exception("Roadside runtime instances missing.");
string report="{\n  \"passed\":true,\n  \"reentry\":2,\n  \"playMode\":true,\n  \"freshRuntimeTerrainClone\":true,\n  \"terrainAndColliderShareClone\":true,\n  \"defaultVariantB\":true,\n  \"grassInstances\":"+grass+",\n  \"rockInstances\":"+rocks+",\n  \"mainCameraEnabled\":true\n}\n";
System.IO.File.WriteAllText("Artifacts/RoadsideV1/RoadsideV1_RuntimeReentry.json",report,new System.Text.UTF8Encoding(false));return "second Play entry passed: fresh data clone, Terrain/Collider share, default B, 50 grass/7 rocks";
